### ISSUE TITLE
Class Dreitier\Util\Logger\LogFacade not found with NADI 3.0.x

### ISSUE THREAD

**Issue by schakko** [NeosIT/active-directory-integration2#178]
Mentioned in https://wordpress.org/support/topic/php8-1-fatalerror-dreitierutilloggerlogfacade/

```
Uncaught Error: Class "Dreitier\\Util\\Logger\\LogFacade" not found in /var/www/html/wp-content/plugins/next-active-directory-integration/src/shared/WordPress/WordPressErrorException.php:50
Stack trace:
#0 /var/www/html/wp-content/plugins/next-active-directory-integration/src/plug-in/User/Manager.php(642): Dreitier\\WordPress\\WordPressErrorException::processWordPressError()
#1 /var/www/html/wp-content/plugins/next-active-directory-integration/src/plug-in/User/Manager.php(577): Dreitier\Nadi\\User\\Manager-&gt;handleEmailAddressOfUser()
#2 /var/www/html/wp-content/plugins/next-active-directory-integration/src/plug-in/User/Manager.php(321): Dreitier\Nadi\\User\\Manager-&gt;updateEmail()
#3 /var/www/html/wp-content/plugins/next-active-directory-integration/src/plug-in/User/LoginSucceededService.php(220): Dreitier\Nadi\\User\\Manager-&gt;update()
#4 /var/www/html/wp-content/plugins/next-active-directory-integration/src/plug-in/User/LoginSucceededService.php(150): Dreitier\Nadi\\User\\LoginSucceededService-&gt;updateUser()
#5 /var/www/html/wp-includes/class-wp-hook.php(303): Dreitier\Nadi\\User\\LoginSucceededService-&gt;updateOrCreateUser()
#6 /var/www/html/wp-includes/plugin.php(189): WP_Hook-&gt;apply_filters()
#7 /var/www/html/wp-content/plugins/next-active-directory-integration/src/plug-in/User/LoginSucceededService.php(85): apply_filters()
#8 /var/www/html/wp-includes/class-wp-hook.php(303): Dreitier\Nadi\\User\\LoginSucceededService-&gt;updateOrCreateAfterSuccessfulLogin()
#9 /var/www/html/wp-includes/plugin.php(189): WP_Hook-&gt;apply_filters()
#10 /var/www/html/wp-includes/pluggable.php(588): apply_filters()
#11 /var/www/html/wp-includes/user.php(95): wp_authenticate()
#12 /var/www/html/wp-login.php(1142): wp_signon()
#13 {main}
  thrown in /var/www/html/wp-content/plugins/next-active-directory-integration/src/shared/WordPress/WordPressErrorException.php on line 50
```

**Comment by schakko** [comment]
Fixed as stated in https://wordpress.org/support/topic/php8-1-fatalerror-dreitierutilloggerlogfacade/#post-16540311
