### ISSUE TITLE
Issue With Email Notification About Blocked Users

### ISSUE THREAD

**Issue by kyleflan** [NeosIT/active-directory-integration2#27]
Wordpress Version: 4.6.1 

I'm aware that Next ADI has not been tested with Wordpress 4.6.1, but I would like to bring this bug to the attention of the developers. When a user has been locked out after the maximum number of login attempts, Next ADI sends an email to the administrator. However, the 'From' email address is invalid; it shows as wordpress@https://sub.domain.com (which I think could be coming from Wordpress's General settings for the site URL).

Redacted error message below:

```
[05-Oct-2016 16:21:35 UTC] PHP Fatal error:  Uncaught phpmailerException: Invalid address: wordpress@https://sub.domain.com; in C:\rc-wordpress\wp-includes\class-phpmailer.php:946
Stack trace:
#0 C:\rc-wordpress\wp-includes\pluggable.php(352): PHPMailer->setFrom('wordpress@https...', 'WordPress', false)
#1 C:\rc-wordpress\wp-content\plugins\next-active-directory-integration\classes\Adi\Mail\Notification.php(215): wp_mail('kyle.flan@n...', '[Site Name...', 'Someone tried t...', Array)
#2 C:\rc-wordpress\wp-content\plugins\next-active-directory-integration\classes\Adi\Mail\Notification.php(195): NextADInt_Adi_Mail_Notification->sendMail('kyle.flan@n...', Object(NextADInt_Adi_Mail_Message))
#3 C:\rc-wordpress\wp-content\plugins\next-active-directory-integration\classes\Adi\Mail\Notification.php(99): NextADInt_Adi_Mail_Notification->sendMails(Object(NextADInt_Adi_Mail_Message))
#4 C:\rc-wordpress\wp-content\plugins\next-active-directory-integration\classes\Adi\Mail\Notification.php(64): NextADInt_Adi_Mail_Notification->sendNotification(Object(Ne in C:\rc-wordpress\wp-includes\class-phpmailer.php on line 946
```

**Comment by MeissnerDa** [comment]
Hello kyleflan,
Thank you for reporting this bug. We will take a look at it today.

**Comment by FatSquirrel93** [comment]
@kyleflan we have started to fix this bug. A new version containing this fix should be live within the next few days. I will let you know, once we have pushed a working version.

Thank you for reporting this issue.
